import { NoteType, Song } from "./types";

const song: Song = {
  artist: "The Kinks",
  name: "Sunny Afternoon",
  key: {
    name: "Dm",
    notes: ["D", "E", "F", "G", "A", "Bb", "C"],
  },
  chords: {
    Dm: ["D", "A", "F"],
    C: ["C", "E", "G"],
    F: ["F", "A", "C"],
    A: ["A", "E", "C#"],
    "G/A": ["G", "A", "E", "C#"],
    "F/A": ["F", "A", "E", "C#"],
    D: ["D", "A", "F#"],
    G7: ["G", "B", "D", "F"],
    C7: ["C", "E", "G", "Bb"],
    A7: ["A", "E", "G", "C#"],
    Bbmaj7: ["Bb", "A", "D", "F"],
  },
  sections: [
    {
      title: "Verse 1",
      notes: [
        {
          name: "D",
          pitch: 38,
          type: NoteType.inChord,
          degree: "i",
          word: "The",
          chord: "Dm",
        },
        {
          name: "D",
          pitch: 38,
          type: NoteType.inChord,
          degree: "i",
          word: "Tax",
          chord: "Dm",
        },
        {
          name: "E",
          pitch: 40,
          type: NoteType.inKey,
          degree: "ii",
          word: "mans",
          chord: "Dm",
        },
        {
          name: "F",
          pitch: 41,
          type: NoteType.inChord,
          degree: "iii",
          word: "tak",
          chord: "Dm",
        },
        {
          name: "G",
          pitch: 43,
          type: NoteType.inKey,
          degree: "iv",
          word: "en",
          chord: "Dm",
        },
        {
          name: "A",
          pitch: 45,
          type: NoteType.inKey,
          degree: "v",
          word: "all",
          chord: "C",
        },
        {
          name: "D",
          pitch: 50,
          type: NoteType.inKey,
          degree: "i",
          word: "my",
          chord: "C",
        },
        {
          name: "C",
          pitch: 48,
          type: NoteType.inChord,
          degree: "vii",
          word: "dough",
          chord: "C",
        },
        {
          name: "F",
          pitch: 41,
          type: NoteType.inChord,
          degree: "iii",
          word: "and",
          chord: "F",
        },
        {
          name: "A",
          pitch: 45,
          type: NoteType.inChord,
          degree: "v",
          word: "left",
          chord: "F",
        },
      ],
    },
    {
      title: "Verse 2",
      notes: [
        {
          name: "D",
          pitch: 38,
          type: NoteType.inChord,
          degree: "i",
          word: "The",
          chord: "Dm",
        },
        {
          name: "D",
          pitch: 38,
          type: NoteType.inChord,
          degree: "i",
          word: "Tax",
          chord: "Dm",
        },
        {
          name: "E",
          pitch: 40,
          type: NoteType.inKey,
          degree: "ii",
          word: "mans",
          chord: "Dm",
        },
        {
          name: "F",
          pitch: 41,
          type: NoteType.inChord,
          degree: "iii",
          word: "tak",
          chord: "Dm",
        },
        {
          name: "G",
          pitch: 43,
          type: NoteType.inKey,
          degree: "iv",
          word: "en",
          chord: "Dm",
        },
        {
          name: "A",
          pitch: 45,
          type: NoteType.inKey,
          degree: "v",
          word: "all",
          chord: "C",
        },
        {
          name: "D",
          pitch: 50,
          type: NoteType.inKey,
          degree: "i",
          word: "my",
          chord: "C",
        },
        {
          name: "C",
          pitch: 48,
          type: NoteType.inChord,
          degree: "vii",
          word: "dough",
          chord: "C",
        },
      ],
    },
  ],
};

export default song;
